language: go

sudo: required

env:
  global:
    - PGPORT=5433
    - PGHOST=localhost
    - DATABASE_URL=postgres://localhost:5433/qb_test

services:
  - mysql
  - postgresql

go:
    - tip

install:
    - go get -u github.com/fatih/structs
    - go get -u github.com/go-sql-driver/mysql
    - go get -u github.com/jmoiron/sqlx
    - go get -u github.com/lib/pq
    - go get -u github.com/mattn/go-sqlite3
    - go get -u github.com/serenize/snaker
    - go get -u github.com/stretchr/testify
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls

script:
    - go test -v -covermode=count -coverprofile=coverage.out
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken 0yIEy3NVX2lXn3KxYzHjkla7EWGjvmLAp

services:
  - mysql
  - postgresql

addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: 9.5

before_script:
  - mysql -e 'create database IF NOT EXISTS qb_test;'
  - sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql -U postgres -c 'CREATE DATABASE qb_test;'