language: go
sudo: true
go:
    - tip
install:
    - go get -u github.com/fatih/structs
    - go get -u github.com/go-sql-driver/mysql
    - go get -u github.com/jmoiron/sqlx
    - go get -u github.com/lib/pq
    - go get -u github.com/mattn/go-sqlite3
    - go get -u github.com/serenize/snaker
    - go get -u github.com/stretchr/testify
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
script:
    - go test -v -covermode=count -coverprofile=coverage.out
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken 0yIEy3NVX2lXn3KxYzHjkla7EWGjvmLAp
before_script:
  - mysql -e 'create database IF NOT EXISTS qb_test;'
  - psql -c 'create database qb_test;' -U postgres
addons:
        postgresql: "9.5"
before_install:
- sudo /etc/init.d/postgresql stop
- wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
- sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
- sudo apt-get update
- sudo apt-get install postgresql-9.5
services:
  - mysql
  - postgresql
